version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - services_microservices-network

networks:
  services_microservices-network:
    external: true
