version: '3.8'
services:
  booking-service:
    build: .
    ports:
      - '3002:3002'
    environment:
      - DATABASE_URL=postgresql://admin:admin@booking-db:5432/booking_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - booking-db
    networks:
      - services_microservices-network

  booking-db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking_db
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - services_microservices-network

networks:
  services_microservices-network:
    external: true

volumes:
  booking_db_data:
