services:
  notifications-service:
    build: .
    volumes:
      - .:/app
    ports:
      - '${LOCAL_PORT}:${PORT}'
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - services_microservices-network
networks:
  services_microservices-network:
    external: true
