version: '3.8'
services:
  user-service:
    build: .
    volumes:
      - .:/app
    ports:
      - '${LOCAL_PORT}:${PORT}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - user-db
    networks:
      - services_microservices-network

  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "${DB_LOCAL_PORT}:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    networks:
      - services_microservices-network


networks:
  services_microservices-network:
    external: true

volumes:
  user_db_data: