import { Controller, UsePipes, Post, Body } from '@nestjs/common';
import { TwoFactorService } from './two-factor.service';
import { BasicReturnType, GetQRCodeReturn } from '../interfaces/auth';
import { ValidationPipe } from '../../users/pipes/validation.pipe';
import { VerifyOptDto } from '../dto';
import { SharedService } from '../shared/shared.service';
import { User, IUserFromHeaders } from '../decorators/request-user-decorator';

@Controller('auth/two-factor')
@UsePipes(ValidationPipe)
export class TwoFactorController {
  constructor(
    private readonly twoFactorService: TwoFactorService,
    private readonly sharedService: SharedService,
  ) {}

  /**
   * Generate Qr code for the user
   * Generates a QR code for the user to set up two-factor authentication.
   *
   * @returns BasicReturnType with the generated QR code data.
   */
  @Post('generate-qr-code')
  async generateQrCode(
    @User() user: IUserFromHeaders,
  ): Promise<BasicReturnType<GetQRCodeReturn>> {
    const qrCode = await this.twoFactorService.getQrCode(user.id, user.email);
    return { success: true, data: { code: qrCode } };
  }

  /**
   * Verify otp for the two factor
   * Verifies the OTP code generated by the user's authenticator app.
   *
   * @param data VerifyOptDto - Contains the user's email and OTP code.
   * @returns BasicReturnType with a response indicating whether the OTP was verified.
   */
  @Post('verify-otp')
  async verifyOTP(
    @Body() data: VerifyOptDto,
  ): Promise<BasicReturnType<{ verified: boolean }>> {
    const res = await this.twoFactorService.verifyOtp(data);
    return { success: true, data: { verified: res } };
  }
}
